# Gradle performance/stability
org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1536m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.daemon=true
org.gradle.vfs.watch=true

# Android / React Native
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
android.enableR8.fullMode=false

# Hermes / New Architecture
hermesEnabled=true
reactNativeArchitectures=arm64-v8a,x86_64

# Expo native packaging
expo.useLegacyPackaging=false
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false
