#!/bin/sh
# Phase 8 — validation against real scripts, per the build plan:
# run nhzsh against real .sh scripts unmodified, and log every construct
# that fails as the real-world signal for what to build next.
set -u
cd "$(dirname "$0")/.."
BIN=./nhzsh
REPORT=tests/phase8_report.md
status=0

{
    echo "# nhzsh Phase 8 — Validation Against Real Scripts"
    echo
    echo "_Auto-generated by \`tests/run_phase8.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')._"
    echo
    echo "Scripts under \`tests/scripts/run_*.sh\` use only the v1 grammar"
    echo "(concept doc §5.2) and must run **unmodified**. \`gap_probe.sh\`"
    echo "deliberately exercises out-of-subset constructs and is expected to fail."
    echo
} > "$REPORT"

for s in tests/scripts/run_*.sh; do
    echo "== $s =="
    out="$("$BIN" "$s" 2>&1)"; rc=$?
    printf '%s\n' "$out"
    {
        echo "## \`$s\` — exit $rc"
        echo
        echo '```'
        printf '%s\n' "$out"
        echo '```'
        echo
    } >> "$REPORT"
    if [ $rc -ne 0 ]; then
        status=1
        echo "  -> FAILED (exit $rc)"
    else
        echo "  -> passed"
    fi
done

echo "== tests/scripts/gap_probe.sh (expected to fail) =="
out="$("$BIN" tests/scripts/gap_probe.sh 2>&1)"; rc=$?
printf '%s\n' "$out"
{
    echo "## \`tests/scripts/gap_probe.sh\` — exit $rc (failure expected)"
    echo
    echo '```'
    printf '%s\n' "$out"
    echo '```'
    echo
    echo "## Unsupported constructs detected (candidates for the next iteration)"
    echo
    echo "Per the build plan, this is the real-world signal for what to build next:"
    echo
    echo "- \`if / then / fi\` conditionals"
    echo "- \`for / do / done\` loops"
    echo "- arithmetic expansion \`\$(( ... ))\`"
    echo "- function definitions (\`name() { ... }\`) — also blocks per-function"
    echo "  library conventions beyond the \`<name>_main\` alias entry point"
    echo "- here-documents and advanced parameter expansion remain explicitly"
    echo "  deferred by the build plan and were not probed here"
    echo
    echo "Note: control flow (\`if\`/\`for\`) appears in neither the v1 build order"
    echo "nor the deferred list; real scripts hit it immediately, so it is the"
    echo "strongest candidate for Stage 8 / v1.1 work."
} >> "$REPORT"

if [ $status -eq 0 ]; then
    echo "PHASE 8: PASSED (all in-subset scripts ran unmodified; report at $REPORT)"
else
    echo "PHASE 8: FAILED (an in-subset script did not run; report at $REPORT)"
    exit 1
fi
