apply plugin: 'com.android.application'

android {
    namespace 'com.example.brokenapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.brokenapp"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.work:work-runtime:2.9.0'
}
