
package com.tycept.wzh2apk;

import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.zip.*;

public class MainActivity extends Activity {
    static final String API = "https://zip-to-apk-ce53.onrender.com";
    static final int PICK_PROJECT=100, PICK_LOGO=101, PICK_GOOGLE=102, PICK_SPLASH=103;
    final int BG=Color.rgb(13,15,17), CARD=Color.rgb(21,23,26), PANEL=Color.rgb(27,29,33), MUTED=Color.rgb(157,161,168), WHITE=Color.rgb(238,240,242), ACCENT=Color.rgb(99,230,213);
    LinearLayout root, content, tabbar; TextView footerLimit, statusText, titleText; Button buildButton;
    EditText appName, packageSuffix, appLinkHost, googleClient, nativeCode, htmlCode, cssCode, jsCode;
    CheckBox signRelease, dex2c, fastCache; Spinner buildType, splashStyle, splashSpeed;
    RadioGroup platformGroup; String sourceMode="zip", codeLang="java", token=null, jobId=null; Uri selectedUri, logoUri, googleUri, customSplashUri;
    SharedPreferences prefs; ExecutorService io=Executors.newCachedThreadPool(); Handler handler=new Handler(Looper.getMainLooper());
    ArrayList<String> selectedPermissions=new ArrayList<>();
    TextView sourceStatus, progress, historyBody;

    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(12,14,16)); prefs=getSharedPreferences("wzh",0); buildShell(); ensureSession(); refreshLimit();}
    TextView tv(String s,float sp,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);t.setPadding(0,6,0,6);return t;}
    GradientDrawable bg(int color,float radius,int stroke,int strokeColor){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);if(stroke>0)g.setStroke(stroke,strokeColor);return g;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(WHITE);b.setTextSize(13);b.setAllCaps(false);b.setBackground(bg(PANEL,16,1,Color.rgb(55,58,63)));b.setPadding(12,4,12,4);return b;}
    EditText edit(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(100,104,110));e.setTextColor(WHITE);e.setTextSize(15);e.setSingleLine(true);e.setPadding(16,0,16,0);e.setBackground(bg(Color.rgb(24,26,30),14,1,Color.rgb(52,55,60)));return e;}
    LinearLayout section(String label,String desc){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(0,16,0,8);box.addView(tv(label.toUpperCase(Locale.US),12,ACCENT)); if(desc!=null)box.addView(tv(desc,13,MUTED)); return box;}
    void addFull(View v,int top){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,ViewGroup.LayoutParams.WRAP_CONTENT);lp.setMargins(0,top,0,0);content.addView(v,lp);}

    void buildShell(){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
        LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(18,12,12,10);header.setBackgroundColor(Color.BLACK);
        TextView logo=tv("↗",28,ACCENT);logo.setGravity(Gravity.CENTER);logo.setBackground(bg(Color.BLACK,0,2,WHITE));header.addView(logo,new LinearLayout.LayoutParams(58,58));
        LinearLayout headText=new LinearLayout(this);headText.setOrientation(LinearLayout.VERTICAL);headText.setPadding(16,0,0,0);headText.addView(tv("WZH 2 APK",23,WHITE));headText.addView(tv(".zip  →  .apk  ·  by Tycept",13,MUTED));header.addView(headText,new LinearLayout.LayoutParams(0,-2,1));
        Button refresh=btn("↻");refresh.setTextSize(25);refresh.setOnClickListener(v->{ensureSession();refreshLimit();});header.addView(refresh,new LinearLayout.LayoutParams(54,54));
        Button help=btn("?");help.setTextSize(20);help.setOnClickListener(v->helpDialog());header.addView(help,new LinearLayout.LayoutParams(54,54)); root.addView(header);
        tabbar=new LinearLayout(this);tabbar.setPadding(8,8,8,8);tabbar.setBackgroundColor(Color.rgb(17,19,22)); String[] tabs={"Build","Options","History","Progress"};
        for(String x:tabs){Button t=btn(x);t.setTextSize(14);t.setTag(x);t.setOnClickListener(v->showTab((String)v.getTag()));tabbar.addView(t,new LinearLayout.LayoutParams(0,48,1));} root.addView(tabbar);
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(24,6,24,120);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout footer=new LinearLayout(this);footer.setOrientation(LinearLayout.VERTICAL);footer.setPadding(24,8,24,10);footer.setBackgroundColor(Color.rgb(10,11,13));footerLimit=tv("Builds today: —",13,MUTED);footerLimit.setGravity(Gravity.CENTER);footer.addView(footerLimit);buildButton=btn("BUILD APK");buildButton.setTextSize(16);buildButton.setEnabled(false);buildButton.setOnClickListener(v->startBuild());footer.addView(buildButton,new LinearLayout.LayoutParams(-1,58));root.addView(footer);setContentView(root);showTab("Build");
    }

    void clear(){content.removeAllViews();}
    void showTab(String tab){clear(); if(tab.equals("Build"))buildTab(); else if(tab.equals("Options"))optionsTab(); else if(tab.equals("History"))historyTab(); else progressTab();}

    void buildTab(){
        addFull(tv("Build your app",27,WHITE),12);addFull(tv("Turn a ZIP project, website, or Java/Kotlin source into an installable Android build.",14,MUTED),0);
        LinearLayout src=section("Source","Choose what you're starting from."); addFull(src,12);
        LinearLayout choices=new LinearLayout(this);choices.setOrientation(LinearLayout.VERTICAL);
        String[] labels={"Upload File","Website link","Write code"};for(String s:labels){Button b=btn((sourceMode.equals(s.equals("Upload File")?"zip":s.equals("Website link")?"url":"code"))?"✓  "+s:s);b.setOnClickListener(v->{sourceMode=s.equals("Upload File")?"zip":s.equals("Website link")?"url":"code";showTab("Build");});choices.addView(b,new LinearLayout.LayoutParams(-1,54));}
        addFull(choices,0);
        if(sourceMode.equals("zip"))buildZipSource(); else if(sourceMode.equals("url"))buildUrlSource(); else buildCodeSource();
        addFull(tv("Build target",12,ACCENT),20); LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.HORIZONTAL);RadioGroup rg=new RadioGroup(this);rg.setOrientation(RadioGroup.HORIZONTAL);RadioButton a=new RadioButton(this);a.setText("Android");a.setTextColor(WHITE);a.setChecked(true);RadioButton w=new RadioButton(this);w.setText("Windows");w.setTextColor(MUTED);rg.addView(a);rg.addView(w);p.addView(rg);addFull(p,0);
        buildButton.setEnabled(sourceMode.equals("url") || selectedUri!=null || (sourceMode.equals("code") && ((codeLang.equals("html")?htmlCode:nativeCode)!=null && ((codeLang.equals("html")?htmlCode:nativeCode).getText().toString().trim().length()>0))));
    }
    void buildZipSource(){Button pick=btn("SELECT PROJECT ZIP / HTML");pick.setOnClickListener(v->pickFile(PICK_PROJECT,"application/zip,text/html,application/octet-stream"));addFull(pick,16);sourceStatus=tv(selectedUri==null?"No project selected":"Selected: "+selectedUri.getLastPathSegment(),14,MUTED);addFull(sourceStatus,4);}
    void buildUrlSource(){EditText url=edit("https://example.com");url.setText(prefs.getString("remoteUrl",""));url.setTag("remoteUrl");addFull(url,16);Button use=btn("USE THIS WEBSITE");use.setOnClickListener(v->{prefs.edit().putString("remoteUrl",url.getText().toString().trim()).apply();sourceStatus.setText("Website URL ready.");buildButton.setEnabled(true);});addFull(use,8);sourceStatus=tv("Website link builds use remoteUrl on the server.",13,MUTED);addFull(sourceStatus,4);}
    void buildCodeSource(){LinearLayout langs=new LinearLayout(this);for(String l:new String[]{"Website","Java","Kotlin"}){Button b=btn((codeLang.equals(l.toLowerCase(Locale.US))?"✓  ":"")+l);b.setOnClickListener(v->{codeLang=l.toLowerCase(Locale.US);showTab("Build");});langs.addView(b,new LinearLayout.LayoutParams(0,52,1));}addFull(langs,16);
        if(codeLang.equals("html")){htmlCode=codeEditor("<!doctype html>\n<html><body><h1>Hello from WZH</h1></body></html>");addFull(htmlCode,8);}
        else {nativeCode=codeEditor(codeLang.equals("java")?javaTemplate("com.example.myapp"):kotlinTemplate("com.example.myapp"));addFull(nativeCode,8);}
        Button reset=btn("RESET TEMPLATE");reset.setOnClickListener(v->{if(codeLang.equals("html"))htmlCode.setText("<!doctype html>\n<html><body><h1>Hello from WZH</h1></body></html>");else nativeCode.setText(codeLang.equals("java")?javaTemplate(derivedPackage()):kotlinTemplate(derivedPackage()));});addFull(reset,8);
    }
    EditText codeEditor(String text){EditText e=new EditText(this);e.setText(text);e.setTextColor(Color.rgb(220,225,228));e.setTextSize(13);e.setGravity(Gravity.TOP|Gravity.START);e.setTypeface(Typeface.MONOSPACE);e.setPadding(14,14,14,14);e.setBackground(bg(Color.rgb(10,12,14),14,1,Color.rgb(54,58,63)));e.setMinHeight(260);e.setSingleLine(false);return e;}
    String derivedPackage(){String s=packageSuffix==null?"":packageSuffix.getText().toString().trim();if(s.length()==0)s=appName==null?"myapp":appName.getText().toString().trim();if(s.length()==0)s="myapp";s=s.toLowerCase(Locale.US).replaceAll("[^a-z0-9]+",".").replaceAll("\\.+",".");return "com."+(s.length()==0?"myapp":s);}
    String javaTemplate(String pkg){return "package "+pkg+";\n\nimport android.app.Activity;\nimport android.os.Bundle;\nimport android.widget.TextView;\n\npublic class MainActivity extends Activity {\n    @Override protected void onCreate(Bundle savedInstanceState) {\n        super.onCreate(savedInstanceState);\n        TextView tv = new TextView(this);\n        tv.setText(\"Hello from Java!\");\n        tv.setTextSize(20);\n        tv.setPadding(40,40,40,40);\n        setContentView(tv);\n    }\n}\n";}
    String kotlinTemplate(String pkg){return "package "+pkg+"\n\nimport android.app.Activity\nimport android.os.Bundle\nimport android.widget.TextView\n\nclass MainActivity : Activity() {\n    override fun onCreate(savedInstanceState: Bundle?) {\n        super.onCreate(savedInstanceState)\n        val tv = TextView(this)\n        tv.text = \"Hello from Kotlin!\"\n        tv.textSize = 20f\n        tv.setPadding(40,40,40,40)\n        setContentView(tv)\n    }\n}\n";}

    void optionsTab(){
        addFull(tv("Options",27,WHITE),12);addFull(tv("Configure the Android build without changing your project source.",14,MUTED),0);
        addFull(section("App details","Identity used by the generated Android project."),12);appName=edit("App name");appName.setText(prefs.getString("appName",""));addFull(appName,4);packageSuffix=edit("Package suffix (optional)");packageSuffix.setText(prefs.getString("pkg",""));addFull(packageSuffix,8);appLinkHost=edit("App link host (optional)");addFull(appLinkHost,8);googleClient=edit("Google web client ID (optional)");addFull(googleClient,8);
        addFull(section("Output","Choose APK/AAB and build behavior."),18);buildType=new Spinner(this);buildType.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"APK — Installable","AAB — Play Store"}));addFull(buildType,4);
        addFull(section("Protection","Build-time hardening options."),18);dex2c=new CheckBox(this);dex2c.setText("Harden with Dex2C");dex2c.setTextColor(WHITE);addFull(dex2c,0);signRelease=new CheckBox(this);signRelease.setText("Sign release build");signRelease.setTextColor(WHITE);signRelease.setChecked(true);addFull(signRelease,0);fastCache=new CheckBox(this);fastCache.setText("Fast cache");fastCache.setTextColor(WHITE);addFull(fastCache,0);
        addFull(section("Startup loading","Select the splash animation and speed."),18);splashStyle=new Spinner(this);splashStyle.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Off","Tumble","Fade","Typewriter","Pulse","Slide","Custom"}));addFull(splashStyle,4);splashSpeed=new Spinner(this);splashSpeed.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Normal","Slow","Fast"}));addFull(splashSpeed,4);
        addFull(section("Permissions","Optional Android permissions sent to the server."),18);String[] perms={"Internet","Network state","Notifications","Keep screen awake","Background tasks","Biometric unlock","Camera","Microphone","Photos","Videos","Audio files","Precise location","Approximate location","Background location","Files & media (legacy)","Read contacts","Edit contacts","Read calendar","Edit calendar","Make calls","Phone state","Call log","Read SMS","Send SMS","Bluetooth","Nearby Wi-Fi devices","Body sensors","Physical activity","Vibrate"};for(String p:perms){CheckBox c=new CheckBox(this);c.setText(p);c.setTextColor(WHITE);c.setButtonTintList(new android.content.res.ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{ACCENT,Color.GRAY}));boolean on=p.equals("Internet")||p.equals("Network state")||p.equals("Camera")||p.equals("Microphone")||p.equals("Precise location")||p.equals("Approximate location")||p.equals("Files & media (legacy)")||p.equals("Vibrate");c.setChecked(on);c.setTag(permissionId(p));selectedPermissions.add(permissionId(p));addFull(c,0);}
        Button save=btn("SAVE OPTIONS");save.setOnClickListener(v->{prefs.edit().putString("appName",appName.getText().toString()).putString("pkg",packageSuffix.getText().toString()).apply();Toast.makeText(this,"Options saved",Toast.LENGTH_SHORT).show();});addFull(save,20);
    }
    String permissionId(String p){return p.toLowerCase(Locale.US).replace(" ","_").replace("&","and").replace("(","").replace(")","").replace("-","_");}

    void historyTab(){addFull(tv("Build history",27,WHITE),12);addFull(tv("Your past builds from the WZH server.",14,MUTED),0);Button refresh=btn("REFRESH HISTORY");refresh.setOnClickListener(v->loadHistory());addFull(refresh,14);historyBody=tv("Loading…",14,MUTED);addFull(historyBody,12);loadHistory();}
    void progressTab(){addFull(tv("Build progress",27,WHITE),12);statusText=tv(jobId==null?"No active build.":"Job: "+jobId,15,WHITE);addFull(statusText,12);progress=tv("Waiting…",14,MUTED);addFull(progress,8);Button cancel=btn("CANCEL BUILD");cancel.setOnClickListener(v->cancelBuild());addFull(cancel,14);}

    void ensureSession(){io.execute(()->{try{String body=get(API+"/api/session",null);token=new JSONObject(body).optString("token",null);runOnUiThread(()->Toast.makeText(this,token==null?"Session unavailable":"Build session ready",Toast.LENGTH_SHORT).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Server session: "+shortErr(e),Toast.LENGTH_LONG).show());}});}
    void refreshLimit(){io.execute(()->{try{JSONObject o=new JSONObject(get(API+"/api/build-limit",null));String s="Builds today: "+o.optInt("used")+"/"+o.optInt("limit")+" used";runOnUiThread(()->footerLimit.setText(s));}catch(Exception ignored){}});}
    String get(String url,String t)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(30000);c.setReadTimeout(30000);if(t!=null)c.setRequestProperty("X-Session-Token",t);c.setRequestProperty("Accept","application/json");c.setRequestProperty("Origin",API);int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();String s=read(in);if(code<200||code>=300)throw new IOException("HTTP "+code+" "+s);return s;}
    String postJson(String url,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(30000);c.setReadTimeout(30000);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Accept","application/json");if(token!=null)c.setRequestProperty("X-Session-Token",token);c.setRequestProperty("Origin",API);c.getOutputStream().write(body.getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();String s=read(code>=400?c.getErrorStream():c.getInputStream());if(code<200||code>=300)throw new IOException("HTTP "+code+" "+s);return s;}
    String read(InputStream in)throws Exception{if(in==null)return "";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x).append('\n');return b.toString();}
    String shortErr(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}

    void startBuild(){saveOptionsSilent();io.execute(()->{try{if(token==null){String b=get(API+"/api/session",null);token=new JSONObject(b).optString("token");}File zip=prepareProject();String boundary="----WZH"+System.currentTimeMillis();HttpURLConnection c=(HttpURLConnection)new URL(API+"/api/build").openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(60000);c.setReadTimeout(120000);c.setRequestProperty("X-Session-Token",token);c.setRequestProperty("Origin",API);c.setRequestProperty("Content-Type","multipart/form-data; boundary="+boundary);OutputStream out=c.getOutputStream();Multipart mp=new Multipart(out,boundary);mp.file("projectZip",zip.getName(),"application/zip",zip);mp.text("buildType",buildType.getSelectedItemPosition()==1?"aab":"apk");mp.text("platform","android");mp.text("clientId",prefs.getString("clientId",UUID.randomUUID().toString()));mp.text("signRelease",String.valueOf(signRelease.isChecked()));mp.text("dex2c",String.valueOf(dex2c.isChecked()));mp.text("cacheMode",fastCache.isChecked()?"fast":"fresh");mp.text("splashStyle",splashValue());mp.text("splashSpeed",splashSpeed==null?"normal":splashSpeed.getSelectedItem().toString().toLowerCase(Locale.US));if(appName!=null&&!appName.getText().toString().trim().isEmpty())mp.text("appName",appName.getText().toString().trim());if(packageSuffix!=null&&!packageSuffix.getText().toString().trim().isEmpty())mp.text("packageSuffix",packageSuffix.getText().toString().trim());if(appLinkHost!=null&&!appLinkHost.getText().toString().trim().isEmpty())mp.text("appLinkHost",appLinkHost.getText().toString().trim());mp.text("permissions",new JSONArray(selectedPermissions).toString());if(sourceMode.equals("url"))mp.text("remoteUrl",prefs.getString("remoteUrl",""));mp.end();int code=c.getResponseCode();String response=read(code>=400?c.getErrorStream():c.getInputStream());if(code==403){token=new JSONObject(get(API+"/api/session",null)).optString("token");throw new IOException("Session expired. Tap Build again to retry with a fresh session.");}if(code<200||code>=300)throw new IOException("Server HTTP "+code+": "+response);JSONObject o=new JSONObject(response);jobId=o.optString("jobId",null);refreshLimit();runOnUiThread(()->{Toast.makeText(this,"Build started",Toast.LENGTH_SHORT).show();showTab("Progress");poll();});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Build failed: "+shortErr(e),Toast.LENGTH_LONG).show());}});}
    String splashValue(){if(splashStyle==null)return "off";String x=splashStyle.getSelectedItem().toString().toLowerCase(Locale.US);return x.equals("off")?"off":x;}
    void poll(){if(jobId==null)return;io.execute(()->{try{String body=get(API+"/api/status/"+URLEncoder.encode(jobId,"UTF-8"),token);JSONObject o=new JSONObject(body);runOnUiThread(()->{if(progress!=null){String msg=o.optString("message",o.optString("status","Building…"));progress.setText(msg+"\n\n"+o.optString("log",""));}statusTextIf();});String st=o.optString("status","").toLowerCase(Locale.US);if(st.contains("done")||st.contains("success")||st.contains("error")||st.contains("failed")||st.contains("cancel")){return;}handler.postDelayed(this::poll,2000);}catch(Exception e){handler.postDelayed(this::poll,4000);}});}
    void statusTextIf(){if(statusText!=null)statusText.setText("Job: "+jobId+"\nLive server status");}
    void cancelBuild(){if(jobId==null)return;io.execute(()->{try{postJson(API+"/api/cancel/"+jobId,"{}");runOnUiThread(()->Toast.makeText(this,"Build cancelled",Toast.LENGTH_SHORT).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Cancel failed: "+shortErr(e),Toast.LENGTH_LONG).show());}});}
    void loadHistory(){if(historyBody==null)return;io.execute(()->{try{String cid=prefs.getString("clientId","");String b=get(API+"/api/history?clientId="+URLEncoder.encode(cid,"UTF-8"),token);runOnUiThread(()->historyBody.setText(formatHistory(b)));}catch(Exception e){runOnUiThread(()->historyBody.setText("Could not load history.\n"+shortErr(e)));}});}
    String formatHistory(String raw){try{JSONArray a=new JSONArray(raw);StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)s.append("• ").append(o.optString("appName",o.optString("jobId","Build"))).append(" — ").append(o.optString("status","unknown")).append('\n');}return s.length()==0?"No builds yet.":s.toString();}catch(Exception e){try{return new JSONObject(raw).toString(2);}catch(Exception x){return raw;}}}

    File prepareProject()throws Exception{File dir=new File(getCacheDir(),"wzh_build");if(dir.exists())delete(dir);dir.mkdirs();File zip=new File(dir,"project.zip");if(sourceMode.equals("zip")&&selectedUri!=null){copyUri(selectedUri,zip);return zip;}if(sourceMode.equals("url")){createHtmlZip(zip,prefs.getString("remoteUrl",""));return zip;}if(codeLang.equals("html")){createHtmlZip(zip,htmlCode.getText().toString());return zip;}createNativeZip(zip);return zip;}
    void copyUri(Uri u,File f)throws Exception{InputStream in=getContentResolver().openInputStream(u);FileOutputStream out=new FileOutputStream(f);byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();out.close();}
    void createHtmlZip(File f,String html)throws Exception{ZipOutputStream z=new ZipOutputStream(new FileOutputStream(f));addZip(z,"index.html",html.getBytes(StandardCharsets.UTF_8));z.close();}
    void createNativeZip(File f)throws Exception{String pkg=derivedPackage();String path=pkg.replace('.','/');String body=nativeCode.getText().toString();body=body.replaceFirst("(?s)^\\s*package\\s+[\\w.]+;?\\s*","");String src="package "+pkg+(codeLang.equals("java")?";":"")+"\n\n"+body;ZipOutputStream z=new ZipOutputStream(new FileOutputStream(f));addZip(z,"settings.gradle",settingsGradle());addZip(z,"build.gradle",codeLang.equals("kotlin")?"plugins { id 'com.android.application' version '8.7.2' apply false\n    id 'org.jetbrains.kotlin.android' version '1.9.24' apply false\n}\n":"plugins { id 'com.android.application' version '8.7.2' apply false }\n");addZip(z,"gradle.properties", "android.useAndroidX=true\norg.gradle.jvmargs=-Xmx2048m\n");addZip(z,"app/build.gradle",nativeAppGradle(pkg));addZip(z,"app/src/main/AndroidManifest.xml",nativeManifest(pkg));addZip(z,"app/src/main/res/values/strings.xml", "<resources><string name=\"app_name\">"+(appName==null?"My App":appName.getText().toString().trim())+"</string></resources>");addZip(z,"app/src/main/res/values/styles.xml","<resources><style name=\"AppTheme\" parent=\"android:style/Theme.Material.NoActionBar\"></style></resources>");addZip(z,"app/src/main/"+(codeLang.equals("kotlin")?"kotlin":"java")+"/"+path+"/MainActivity."+(codeLang.equals("kotlin")?"kt":"java"),src);z.close();}
    String settingsGradle(){return "pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }\nrootProject.name='GeneratedApp'\ninclude ':app'\n";}
    String nativeAppGradle(String pkg){return "plugins { id 'com.android.application' "+(codeLang.equals("kotlin")?"\n id 'org.jetbrains.kotlin.android' ":"")+"}\nandroid { namespace '"+pkg+"'; compileSdk 35; defaultConfig { applicationId '"+pkg+"'; minSdk 23; targetSdk 35; versionCode 1; versionName '1.0' } buildTypes { release { minifyEnabled false } } compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 } "+(codeLang.equals("kotlin")?"kotlinOptions { jvmTarget = '17' }":"")+" }\n";}
    String nativeManifest(String pkg){return "<?xml version=\"1.0\" encoding=\"utf-8\"?><manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"><application android:theme=\"@style/AppTheme\" android:label=\"WZH Generated App\"><activity android:name=\"."+(codeLang.equals("kotlin")?"MainActivity":"MainActivity")+"\" android:exported=\"true\"><intent-filter><action android:name=\"android.intent.action.MAIN\"/><category android:name=\"android.intent.category.LAUNCHER\"/></intent-filter></activity></application></manifest>";}
    void addZip(ZipOutputStream z,String name,byte[] b)throws Exception{z.putNextEntry(new ZipEntry(name));z.write(b);z.closeEntry();}void addZip(ZipOutputStream z,String name,String s)throws Exception{addZip(z,name,s.getBytes(StandardCharsets.UTF_8));}
    void delete(File f){if(f.isDirectory()){File[] a=f.listFiles();if(a!=null)for(File x:a)delete(x);}f.delete();}
    void saveOptionsSilent(){if(appName!=null)prefs.edit().putString("appName",appName.getText().toString()).putString("pkg",packageSuffix==null?"":packageSuffix.getText().toString()).apply();}
    void pickFile(int req,String mime){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,false);startActivityForResult(i,req);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;Uri u=d.getData();if(r==PICK_PROJECT){selectedUri=u;if(sourceStatus!=null)sourceStatus.setText("Selected: "+u.getLastPathSegment());buildButton.setEnabled(true);}else if(r==PICK_LOGO)logoUri=u;else if(r==PICK_GOOGLE)googleUri=u;else if(r==PICK_SPLASH)customSplashUri=u;}
    void helpDialog(){new AlertDialog.Builder(this).setTitle("WZH 2 APK").setMessage("Native Android client for the WZH build service. It keeps the main Build, Options, History and Progress flows and talks directly to your Render API.\n\nIf the server rejects native requests because of Origin policy, the backend must allow the app's native client; an Android app cannot satisfy a browser-only CORS policy by itself.").setPositiveButton("OK",null).show();}
    String nativeManifestDummy(){return "";}
    static class Multipart{OutputStream o;String b;Multipart(OutputStream o,String b){this.o=o;this.b=b;}void text(String n,String v)throws Exception{head(n,null,null);o.write(v.getBytes(StandardCharsets.UTF_8));o.write("\r\n".getBytes());}void file(String n,String fn,String type,File f)throws Exception{head(n,fn,type);FileInputStream in=new FileInputStream(f);byte[] x=new byte[8192];int k;while((k=in.read(x))>0)o.write(x,0,k);in.close();o.write("\r\n".getBytes());}void head(String n,String fn,String type)throws Exception{o.write(("--"+b+"\r\n").getBytes());if(fn==null)o.write(("Content-Disposition: form-data; name=\""+n+"\"\r\n\r\n").getBytes());else{o.write(("Content-Disposition: form-data; name=\""+n+"\"; filename=\""+fn+"\"\r\n").getBytes());o.write(("Content-Type: "+type+"\r\n\r\n").getBytes());}}void end()throws Exception{o.write(("--"+b+"--\r\n").getBytes());o.flush();}}
}
