package com.ryan.vietsubai.editor

import android.content.Context
import com.ryan.vietsubai.model.EditorDraft
import org.json.JSONArray
import org.json.JSONObject
import com.ryan.vietsubai.model.BlurCropRegion
import com.ryan.vietsubai.model.FontAsset
import com.ryan.vietsubai.model.SubtitleSegment

class EditorAutosave(context: Context) {
    private val prefs=context.getSharedPreferences("editor_autosave",Context.MODE_PRIVATE)
    fun save(d:EditorDraft){
        val o=JSONObject().put("videoUri",d.videoUri).put("videoName",d.videoName).put("speed",d.speed).put("volume",d.volume).put("subtitleText",d.subtitleText).put("selectedTool",d.selectedTool).put("activeFontId",d.activeFontId).put("ocrScanFps",d.ocrScanFps).put("ttsRate",d.ttsRate).put("ttsPadMs",d.ttsPadMs).put("ttsSyncLabel",d.ttsSyncLabel)
        o.put("fonts",JSONArray(d.fonts.map{JSONObject().put("id",it.id).put("name",it.name).put("uri",it.uri)}))
        o.put("blur",JSONArray(d.blurRegions.map{JSONObject().put("id",it.id).put("l",it.left).put("t",it.top).put("r",it.right).put("b",it.bottom).put("s",it.startMs).put("e",it.endMs)})).put("subtitleRegion",JSONObject().put("l",d.subtitleRegion.left).put("t",d.subtitleRegion.top).put("r",d.subtitleRegion.right).put("b",d.subtitleRegion.bottom))
        o.put("style",JSONObject().put("fontSize",d.subtitleStyle.fontSize).put("textColor",d.subtitleStyle.textColor).put("strokeColor",d.subtitleStyle.strokeColor).put("strokeWidth",d.subtitleStyle.strokeWidth).put("shadow",d.subtitleStyle.shadow).put("backgroundColor",d.subtitleStyle.backgroundColor).put("backgroundRadius",d.subtitleStyle.backgroundRadius).put("align",d.subtitleStyle.align).put("bold",d.subtitleStyle.bold).put("italic",d.subtitleStyle.italic).put("lineSpacing",d.subtitleStyle.lineSpacing).put("letterSpacing",d.subtitleStyle.letterSpacing).put("animation",d.subtitleStyle.animation).put("animationMs",d.subtitleStyle.animationMs))
        o.put("crop",JSONObject().put("preset",d.crop.preset).put("zoom",d.crop.zoom).put("offsetX",d.crop.offsetX).put("offsetY",d.crop.offsetY))
        o.put("hardware",d.renderHardwareAcceleration).put("fps",d.renderOutputFps).put("autoOcr",d.autoOcr).put("removeOriginalSubtitle",d.removeOriginalSubtitle)
        o.put("subs",JSONArray(d.subtitleSegments.map{JSONObject().put("start",it.start).put("end",it.end).put("text",it.text).put("translation",it.translation)}))
        prefs.edit().putString("draft",o.toString()).apply()
    }
    fun load():EditorDraft?=runCatching{val o=JSONObject(prefs.getString("draft",null)?:return null);val fonts=o.optJSONArray("fonts")?.let{a->List(a.length()){i->val x=a.getJSONObject(i);FontAsset(x.getString("id"),x.getString("name"),x.getString("uri"))}}?:emptyList();val blur=o.optJSONArray("blur")?.let{a->List(a.length()){i->val x=a.getJSONObject(i);BlurCropRegion(x.getString("id"),x.getDouble("l").toFloat(),x.getDouble("t").toFloat(),x.getDouble("r").toFloat(),x.getDouble("b").toFloat(),x.optLong("s"),x.optLong("e",Long.MAX_VALUE))}}?:emptyList();val subs=o.optJSONArray("subs")?.let{a->List(a.length()){i->val x=a.getJSONObject(i);SubtitleSegment(x.getDouble("start"),x.getDouble("end"),x.getString("text"),x.optString("translation").ifBlank{null})}}?:emptyList();EditorDraft(videoUri=o.optString("videoUri").ifBlank{null},videoName=o.optString("videoName"),speed=o.optDouble("speed",1.0).toFloat(),volume=o.optDouble("volume",1.0).toFloat(),subtitleText=o.optString("subtitleText"),selectedTool=o.optString("selectedTool","trim"),activeFontId=o.optString("activeFontId").ifBlank{null},fonts=fonts,blurRegions=blur,subtitleRegion=o.optJSONObject("subtitleRegion")?.let{x->BlurCropRegion("subtitle",x.getDouble("l").toFloat(),x.getDouble("t").toFloat(),x.getDouble("r").toFloat(),x.getDouble("b").toFloat())}?:BlurCropRegion("subtitle",.08f,.72f,.92f,.96f),subtitleSegments=subs,ocrScanFps=o.optDouble("ocrScanFps",2.0).toFloat(),ttsRate=o.optDouble("ttsRate",1.0).toFloat(),ttsPadMs=o.optLong("ttsPadMs",0),ttsSyncLabel=o.optString("ttsSyncLabel","Chưa đồng bộ"),subtitleStyle=o.optJSONObject("style")?.let{x->com.ryan.vietsubai.model.SubtitleStyle(x.optDouble("fontSize",20.0).toFloat(),x.optLong("textColor",0xFFFFFFFF),x.optLong("strokeColor",0xFF000000),x.optDouble("strokeWidth",3.0).toFloat(),x.optDouble("shadow",6.0).toFloat(),x.optLong("backgroundColor",0L),x.optDouble("backgroundRadius",12.0).toFloat(),x.optInt("align",1),x.optBoolean("bold",true),x.optBoolean("italic",false),x.optDouble("lineSpacing",1.2).toFloat(),x.optDouble("letterSpacing",0.0).toFloat(),x.optString("animation","fade"),x.optInt("animationMs",180))}?:com.ryan.vietsubai.model.SubtitleStyle(),crop=o.optJSONObject("crop")?.let{x->com.ryan.vietsubai.model.CropSettings(x.optString("preset","original"),x.optDouble("zoom",1.0).toFloat(),x.optDouble("offsetX",0.0).toFloat(),x.optDouble("offsetY",0.0).toFloat())}?:com.ryan.vietsubai.model.CropSettings(),renderHardwareAcceleration=o.optBoolean("hardware",true),renderOutputFps=o.optInt("fps",30),autoOcr=o.optBoolean("autoOcr",false),removeOriginalSubtitle=o.optBoolean("removeOriginalSubtitle",false))}.getOrNull()
    fun clear(){prefs.edit().remove("draft").apply()}
}
